export const initData = {
  id: "board-1",
  columnOrder: ["column-3", "column-2", "column-1"],
  columns: [
    {
      id: "column-1",
      boardId: "board-1",
      title: "Todo 1",
      cardOrder: [
        "card-1",
        "card-2",
        "card-3",
        "card-4",
        "card-51",
        "card-61",
        "card-71",
        "card-81",
        "card-91",
        "card-101",
        "card-102",
        "card-103",
      ],
      cards: [
        {
          id: "card-1",
          boardId: "board-1",
          columnId: "column-1",
          title: "Title card 1",
        },
        {
          id: "card-2",
          boardId: "board-1",
          columnId: "column-1",
          title: "Title card 2",
        },
        {
          id: "card-3",
          boardId: "board-1",
          columnId: "column-1",
          title: "Title card 3",
        },
        {
          id: "card-4",
          boardId: "board-1",
          columnId: "column-1",
          title: "Title card 4",
        },
        {
          id: "card-51",
          boardId: "board-1",
          columnId: "column-1",
          title: "Title card 51",
        },
        {
          id: "card-61",
          boardId: "board-1",
          columnId: "column-1",
          title: "Title card 61",
        },
        {
          id: "card-71",
          boardId: "board-1",
          columnId: "column-1",
          title: "Title card 71",
        },
        {
          id: "card-81",
          boardId: "board-1",
          columnId: "column-1",
          title: "Title card 81",
        },
        {
          id: "card-91",
          boardId: "board-1",
          columnId: "column-1",
          title: "Title card 91",
        },
        {
          id: "card-101",
          boardId: "board-1",
          columnId: "column-1",
          title: "Title card 101",
        },
        {
          id: "card-102",
          boardId: "board-1",
          columnId: "column-1",
          title: "Title card 101",
        },
        {
          id: "card-103",
          boardId: "board-1",
          columnId: "column-1",
          title: "Title card 101",
        },
      ],
    },
    {
      id: "column-2",
      boardId: "board-1",
      title: "Todo 2",
      cardOrder: ["card-6", "card-7", "card-8"],
      cards: [
        {
          id: "card-6",
          boardId: "board-1",
          columnId: "column-2",
          title: "Title card 6",
        },
        {
          id: "card-7",
          boardId: "board-1",
          columnId: "column-2",
          title: "Title card 7",
        },
        {
          id: "card-8",
          boardId: "board-1",
          columnId: "column-2",
          title: "Title card 8",
        },
      ],
    },
    {
      id: "column-3",
      boardId: "board-1",
      title: "Todo 3",
      cardOrder: ["card-9", "card-10"],
      cards: [
        {
          id: "card-9",
          boardId: "board-1",
          columnId: "column-3",
          title: "Title card 9",
        },
        {
          id: "card-10",
          boardId: "board-1",
          columnId: "column-3",
          title: "Title card 10",
        },
      ],
    },
  ],
  title: "",
};
